apiVersion: v1
kind: Service
metadata:
  name: nginx-html-app-svc
  labels:
    app: nginx-html-app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: nginx-html-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-html-app
  labels:
    app: nginx-html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-html-app
  template:
    metadata:
      labels:
        app: nginx-html-app
    spec:
      containers:
      - name: nginx-html-app
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

