name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER:  github-gke-cicd    
  GKE_ZONE: us-central1-c 
  DEPLOYMENT_NAME: nginx-cicd
  IMAGE: micro 
  TAG: 1.0.0

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - name: Set up GKE credentials
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      env:
         ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Docker configuration
      run: |-
        gcloud --quiet auth configure-docker

    - name: Set up GKE credentials
      run: |-
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: Build
      run: |-
        docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .

    - name: Docker setup
      run: |-
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$GKE_ZONE-docker.pkg.dev

    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"

    - name: Setup Kustomization
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Deploy
      run: |-
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide

